### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by japel** [karussell/elasticsearch-reindex#38]
Is there any way to control memory consumption?
I'm trying to reindex ~12000 documents (~14gb) and my heap seems to be too small.
Problem is, I can't extend it because I don't have enough RAM

**Comment by karussell** [comment]
I think there is a parameter to control this (it is years that I've looked in the source ;)). Look up hitsPerPage or something

**Comment by japel** [comment]
found it! thank you very much!
